set preview_images true
set preview_images_method w3m
set mouse_enabled false
set sort_directories_first true
set shorten_title 3
set tilde_in_titlebar true
set sort ctime
set colorscheme custom

map gf cd ~/Documents/Dropbox/_folder/
map gd cd ~/Downloads/
map gs cd /media/storage/
map gp cd ~/Programs/
map gk cd ~/Documents/Dropbox/_skola/

map f console scout -ftsea%space